"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { execFile } = require("node:child_process");
const { boomerangClip } = require("../lib/hero-clip-boomerang");

const FFMPEG_BIN = process.env.GHOST_AGENCY_FFMPEG_BIN || "ffmpeg";

// A real 4-second, 480p, silent mp4 generated by ffmpeg. The test suite creates
// this in a before() hook so it is self-contained and does not depend on an
// external setup step.
let sourcePath = "";
let ffmpegAvailable = true;

function run(bin, args) {
  return new Promise((resolve) => {
    execFile(bin, args, { timeout: 30000, maxBuffer: 1024 * 1024, windowsHide: true }, (error, stdout, stderr) => {
      if (error) return resolve({ ok: false, message: String(error.message || error).slice(0, 300), stderr: String(stderr || "") });
      resolve({ ok: true, stdout: String(stdout || ""), stderr: String(stderr || "") });
    });
  });
}

test.before(async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "wss-boom-test-"));
  sourcePath = path.join(dir, "source4s.mp4");
  const res = await run(FFMPEG_BIN, ["-y", "-loglevel", "error", "-f", "lavfi", "-i", "testsrc2=duration=4:size=854x480:rate=30", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-an", sourcePath]);
  if (!res.ok || !fs.existsSync(sourcePath)) {
    // ffmpeg missing in this environment — the boomerang step is a local-only
    // optimization and degrades gracefully; mark the flag so tests that require
    // ffmpeg skip rather than fail the suite.
    ffmpegAvailable = false;
  }
});

test("boomerangs a 4-second clip into a 12-second hero (3 passes)", async (t) => {
  if (!ffmpegAvailable) return t.skip();
  const source = fs.readFileSync(sourcePath);
  const res = await boomerangClip(source, { passes: 3 });
  assert.equal(res.ok, true, `expected ok, got ${JSON.stringify(res).slice(0, 200)}`);
  assert.equal(res.passes, 3);
  assert.ok(res.bytes && res.bytes.length > 0, "output bytes should be non-empty");
  assert.ok(res.bytes.length <= 4 * 1024 * 1024, "output must be under the 4MB clip cap");
  assert.ok(res.durationSec >= 11.5 && res.durationSec <= 12.5, `duration ${res.durationSec} should be ~12s`);
  assert.ok(res.sourceDurationSec >= 3.9 && res.sourceDurationSec <= 4.1, `source duration ${res.sourceDurationSec} should be ~4s`);
});

test("2 passes produces an ~8-second clip", async (t) => {
  if (!ffmpegAvailable) return t.skip();
  const source = fs.readFileSync(sourcePath);
  const res = await boomerangClip(source, { passes: 2 });
  assert.equal(res.ok, true);
  assert.equal(res.passes, 2);
  assert.ok(res.durationSec >= 7.5 && res.durationSec <= 8.5, `duration ${res.durationSec} should be ~8s`);
});

test("rejects an empty source buffer", async () => {
  const res = await boomerangClip(Buffer.alloc(0));
  assert.equal(res.ok, false);
  assert.equal(res.reason, "boomerang_source_empty");
});

test("rejects a non-mp4 buffer without crashing", async () => {
  const res = await boomerangClip(Buffer.from("not a video at all"));
  assert.equal(res.ok, false);
  assert.ok(res.reason.startsWith("boomerang_source_"));
});
