"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const state=require("../lib/line-state"),quota=require("../lib/line-quota"),runner=require("../lib/line-runner"),adapters=require("../lib/line-adapters");
function gatedRow(extra={}){let r=state.newRow({prospectId:"p1",businessName:"A",city:"Irvine",state:"CA",vertical:"plumbing",now:"2026-08-16T00:00:00Z"});r=state.advanceRow(r,"qualified").row;r=state.advanceRow(r,"mirrored",{previewUrl:"https://p1.wss-ai.com"}).row;r=state.applyGate(r,{pass:true,failed:[],checks:[]}).row;return {...r,...extra};}
test("render-passed no-contact site becomes ready and never queues email",async()=>{let queued=0,written=0;const row=gatedRow({hasEmail:false,contactReady:false});const out=await runner.processRowPhase(row,{lane:"live",batchId:"b"},{writePreviewUrl:async()=>{written++;return {ok:true}},queueEmail:async()=>{queued++;return {ok:true}},env:{GHOST_AGENCY_HERO_AUTOLINE:"0"}});assert.equal(out.ok,true);assert.equal(out.row.status,"ready");assert.equal(written,1);assert.equal(queued,0)});
test("ready is successful terminal but never sendable",()=>{const row=state.advanceRow(gatedRow(),"ready",{previewUrl:"https://p1.wss-ai.com"}).row;const batch={batchId:"b",status:"approved",approval:{at:new Date().toISOString(),typedBatchId:"b",approvedRows:1},pickState:"complete",rows:[row]};assert.equal(state.batchSettled(batch),true);assert.equal(state.batchCounts(batch).ready,1);assert.equal(state.sendableRows(batch).length,0)});
test("ready without a passing gate is stranded work, so the runner reopens it at mirrored with a named reason",async()=>{const row={...state.advanceRow(gatedRow(),"ready",{previewUrl:"https://p1.wss-ai.com"}).row,gate:null,reason:""};const batch={batchId:"b",status:"done",pickState:"complete",rows:[row]};assert.equal(state.batchSettled(batch),false);assert.equal(state.deriveBuildStatus(batch),"building");const out=await runner.processRowPhase(row,{lane:"live",batchId:"b"},{env:{GHOST_AGENCY_HERO_AUTOLINE:"0"}});assert.equal(out.ok,true);assert.equal(out.phase,"render_gate_recovery");assert.equal(out.row.status,"mirrored");assert.equal(out.row.reason,"gate_never_ran")});
test("finished quota counts ready plus queued plus sent",()=>{const batch={requested:3,rows:[{status:"ready",gate:{pass:true}},{status:"queued"},{status:"sent"},{status:"error"}],mineFunnel:[{stage:quota.QUOTA_CONTRACT_STAGE}]};assert.equal(quota.finishedRows(batch).length,3);assert.equal(quota.remainingFinishedQuota(batch),0)});
test("50 mixed completed websites satisfy Mine 50 independent of contactability",()=>{const rows=Array.from({length:50},(_,i)=>(i%3===0?{status:"ready",gate:{pass:true}}:{status:"queued"}));const batch={requested:50,rows,mineFunnel:[{stage:quota.QUOTA_CONTRACT_STAGE}]};const c=state.batchCounts(batch);assert.equal(quota.finishedRows(batch).length,50);assert.equal(quota.remainingFinishedQuota(batch),0);assert.equal(c.ready+c.queued,50)});
test("no-email contact classification does not reject building",()=>{const v=adapters.contactFirstVerdict({record:{},business_name:"A"});assert.equal(v.ok,true);assert.equal(v.contactReady,false);assert.equal(v.email,"")});
