/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SeminarsRouteImport } from './routes/seminars'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArtsRouteImport } from './routes/arts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtsSlugRouteImport } from './routes/arts.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminarsRoute = SeminarsRouteImport.update({
  id: '/seminars',
  path: '/seminars',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtsRoute = ArtsRouteImport.update({
  id: '/arts',
  path: '/arts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtsSlugRoute = ArtsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtsRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arts': typeof ArtsRouteWithChildren
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/seminars': typeof SeminarsRoute
  '/training': typeof TrainingRoute
  '/arts/$slug': typeof ArtsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arts': typeof ArtsRouteWithChildren
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/seminars': typeof SeminarsRoute
  '/training': typeof TrainingRoute
  '/arts/$slug': typeof ArtsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arts': typeof ArtsRouteWithChildren
  '/contact': typeof ContactRoute
  '/media': typeof MediaRoute
  '/seminars': typeof SeminarsRoute
  '/training': typeof TrainingRoute
  '/arts/$slug': typeof ArtsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arts'
    | '/contact'
    | '/media'
    | '/seminars'
    | '/training'
    | '/arts/$slug'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arts'
    | '/contact'
    | '/media'
    | '/seminars'
    | '/training'
    | '/arts/$slug'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/arts'
    | '/contact'
    | '/media'
    | '/seminars'
    | '/training'
    | '/arts/$slug'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtsRoute: typeof ArtsRouteWithChildren
  ContactRoute: typeof ContactRoute
  MediaRoute: typeof MediaRoute
  SeminarsRoute: typeof SeminarsRoute
  TrainingRoute: typeof TrainingRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminars': {
      id: '/seminars'
      path: '/seminars'
      fullPath: '/seminars'
      preLoaderRoute: typeof SeminarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arts': {
      id: '/arts'
      path: '/arts'
      fullPath: '/arts'
      preLoaderRoute: typeof ArtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arts/$slug': {
      id: '/arts/$slug'
      path: '/$slug'
      fullPath: '/arts/$slug'
      preLoaderRoute: typeof ArtsSlugRouteImport
      parentRoute: typeof ArtsRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArtsRouteChildren {
  ArtsSlugRoute: typeof ArtsSlugRoute
}

const ArtsRouteChildren: ArtsRouteChildren = {
  ArtsSlugRoute: ArtsSlugRoute,
}

const ArtsRouteWithChildren = ArtsRoute._addFileChildren(ArtsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtsRoute: ArtsRouteWithChildren,
  ContactRoute: ContactRoute,
  MediaRoute: MediaRoute,
  SeminarsRoute: SeminarsRoute,
  TrainingRoute: TrainingRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
