/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TradeAreaRouteImport } from './routes/$trade.$area'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicRefreshProofRouteImport } from './routes/api/public/refresh-proof'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeAreaRoute = TradeAreaRouteImport.update({
  id: '/$trade/$area',
  path: '/$trade/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshProofRoute = ApiPublicRefreshProofRouteImport.update({
  id: '/api/public/refresh-proof',
  path: '/api/public/refresh-proof',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$trade/$area': typeof TradeAreaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/refresh-proof': typeof ApiPublicRefreshProofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$trade/$area': typeof TradeAreaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/refresh-proof': typeof ApiPublicRefreshProofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$trade/$area': typeof TradeAreaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/refresh-proof': typeof ApiPublicRefreshProofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/$trade/$area'
    | '/api/chat'
    | '/api/public/refresh-proof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/$trade/$area'
    | '/api/chat'
    | '/api/public/refresh-proof'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/$trade/$area'
    | '/api/chat'
    | '/api/public/refresh-proof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradeAreaRoute: typeof TradeAreaRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicRefreshProofRoute: typeof ApiPublicRefreshProofRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$trade/$area': {
      id: '/$trade/$area'
      path: '/$trade/$area'
      fullPath: '/$trade/$area'
      preLoaderRoute: typeof TradeAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-proof': {
      id: '/api/public/refresh-proof'
      path: '/api/public/refresh-proof'
      fullPath: '/api/public/refresh-proof'
      preLoaderRoute: typeof ApiPublicRefreshProofRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradeAreaRoute: TradeAreaRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicRefreshProofRoute: ApiPublicRefreshProofRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
