/**
 * ┌── MIRROR:TEMPLATE-CODE ──────────────────────────────────────────────────
 * │ WHAT THIS FILE HOLDS: the homepage composition — hero, star summary with
 * │ real faces, trust rails, service menu, gallery, map + directions, voice
 * │ answers, review composer, AI concierge, sticky proof bar.
 * │ WHO WRITES IT: nobody — byte-identical in every mirrored client. Section
 * │ order is deliberate (proof above the fold); do not reorder per client.
 * │ EVERY WORD ON THE PAGE COMES FROM: src/trust.config.ts + src/client.config.ts.
 * │ IF A CLIENT LACKS A DATA SET (no gallery, no credentials, no video
 * │ testimonials): delete that key from trust.config.ts — the section removes
 * │ itself. Do NOT edit this file to hide a section.
 * │ FULL SPEC: MIRRORING-ENGINE.md §Page composition
 * └──────────────────────────────────────────────────────────────────────────
 */
import { clientData, sitePlan } from "@/wss-bridge";
import { ClientCopy, ContactBand, HoursText } from "@/components/ClientContent";

import { clientConfig } from "@/client.config";

import { CinematicHero, BrandMark } from "@/components/CinematicHero";
import { LocalMap } from "@/components/LocalMap";
import { ReviewRequestPanel } from "@/components/ReviewRequestPanel";

import { trustConfig } from "@/trust.config";
import { TrustProvider } from "@/trust-widgets/TrustProvider";
import { RatingBadgeCluster } from "@/trust-widgets/components/RatingBadgeCluster";
import { StarSummaryBar } from "@/trust-widgets/components/StarSummaryBar";
import { TrustBadgeRail } from "@/trust-widgets/components/TrustBadgeRail";
import { CounterStatBand } from "@/trust-widgets/components/CounterStatBand";
import { ReviewMarquee } from "@/trust-widgets/components/ReviewMarquee";
import { ReviewSpotlight } from "@/trust-widgets/components/ReviewSpotlight";
import { ReviewWall } from "@/trust-widgets/components/ReviewWall";
import { ServiceMenuGrid } from "@/trust-widgets/components/ServiceMenuGrid";
import { ServiceAreaBanner } from "@/trust-widgets/components/ServiceAreaBanner";
import { GuaranteePanel } from "@/trust-widgets/components/GuaranteePanel";
import { LicenseVerifyBadge } from "@/trust-widgets/components/LicenseVerifyBadge";
import { InsuranceProofPanel } from "@/trust-widgets/components/InsuranceProofPanel";
import { CredentialModal } from "@/trust-widgets/components/CredentialModal";
import { PortfolioLightbox } from "@/trust-widgets/components/PortfolioLightbox";
import { OpenNowStatus } from "@/trust-widgets/components/OpenNowStatus";
import { EmergencyCTABand } from "@/trust-widgets/components/EmergencyCTABand";
import { SocialFollowerBar } from "@/trust-widgets/components/SocialFollowerBar";
import { VoiceAnswerBlock } from "@/trust-widgets/components/VoiceAnswerBlock";
import { SpeakableSchema } from "@/trust-widgets/components/SpeakableSchema";
import { SeoProofBlock } from "@/trust-widgets/components/SeoProofBlock";
import { ProofStickyBar } from "@/trust-widgets/components/ProofStickyBar";
import { BookNowSticky } from "@/trust-widgets/components/BookNowSticky";


export function SectionShell({
  id,
  eyebrow,
  title,
  lede,
  children,
  tone = "base",
}: {
  id?: string;
  eyebrow?: string;
  title?: string;
  lede?: string;
  children: React.ReactNode;
  tone?: "base" | "raised";
}) {
  return (
    <section
      id={id}
      className={
        "reveal-on-scroll relative px-5 py-20 sm:px-8 " +
        (tone === "raised" ? "bg-[color-mix(in_oklab,var(--cream)_5%,transparent)]" : "")
      }
    >
      <div className="mx-auto w-full max-w-[1180px]">
        {(eyebrow || title) && (
          <header className="mb-10 max-w-2xl">
            {eyebrow && (
              <p className="mb-3 text-xs font-semibold uppercase tracking-[0.32em] text-mint">
                {eyebrow}
              </p>
            )}
            {title && (
              <h2 className="font-[Archivo] text-3xl font-extrabold leading-[1.05] tracking-tight text-cream sm:text-5xl">
                {title}
              </h2>
            )}
            {lede && <p className="mt-4 text-base leading-relaxed text-muted-foreground">{lede}</p>}
          </header>
        )}
        {children}
      </div>
    </section>
  );
}

export function Hero({ cfg }: { cfg: typeof trustConfig }) {
  const rating = cfg.proof.ratings?.[0];
  const tel = `tel:${cfg.contact.phone ?? ""}`;
  return (
    <CinematicHero>
      <header className="relative px-5 pb-24 pt-8 sm:px-8">
        <div className="mx-auto w-full max-w-[1180px]">
          <nav className="flex flex-wrap items-center justify-between gap-4">
            <BrandMark />
            <div className="flex flex-wrap items-center gap-3">
              <OpenNowStatus />
              <a
                href={tel}
                className="rounded-full bg-mint px-5 py-2.5 text-sm font-semibold text-primary-foreground shadow-glow transition-transform hover:-translate-y-0.5"
              >
                {cfg.contact.phoneDisplay}
              </a>
            </div>
          </nav>

          <div className="mt-20 grid gap-12 lg:grid-cols-[1.15fr_0.85fr] lg:items-center">
            <div className="animate-rise">
              <p className="mb-5 inline-flex items-center gap-2 rounded-full border border-border bg-[color-mix(in_oklab,var(--petrol-deep)_55%,transparent)] px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.24em] text-mint backdrop-blur">
                <span className="inline-block size-2 animate-pulse-ring rounded-full bg-mint" />
                {clientConfig.hero.kicker}
              </p>
              <h1 className="font-[Archivo] text-[clamp(2.6rem,7vw,5.2rem)] font-extrabold leading-[0.95] tracking-tight text-cream drop-shadow-[0_10px_40px_rgba(0,0,0,.5)]">
                {clientConfig.hero.headline}{" "}
                <em className="text-shimmer font-[Instrument_Serif] not-italic">
                  {clientConfig.hero.headlineAccent}
                </em>{" "}{clientConfig.hero.sub}
              </h1>
              <p className="mt-6 max-w-xl text-lg leading-relaxed text-cream/80">
                {cfg.business.description}
              </p>

              <div className="mt-8 flex flex-wrap items-center gap-4">
                <a
                  href={tel}
                  className="rounded-full bg-coral px-7 py-3.5 text-base font-semibold text-accent-foreground shadow-float transition-transform hover:-translate-y-0.5"
                >
                  Call {cfg.contact.phoneDisplay}
                </a>
                {cfg.contact.bookingUrl && (
                  <a
                    href={cfg.contact.bookingUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="rounded-full border border-border bg-[color-mix(in_oklab,var(--petrol-deep)_50%,transparent)] px-7 py-3.5 text-base font-semibold text-cream backdrop-blur transition-colors hover:border-mint"
                  >
                    Book online
                  </a>
                )}
              </div>

              <div className="mt-10 flex flex-wrap items-center gap-5">
                <StarSummaryBar compact />
              </div>
            </div>

            {rating && <div className="relative animate-float">
              <div className="glass-panel rounded-3xl p-6">
                <p className="text-xs font-semibold uppercase tracking-[0.28em] text-mint">
                  Verified proof
                </p>
                <div className="mt-5">
                  <RatingBadgeCluster />
                </div>
                {rating && (
                  <p className="mt-5 text-sm text-muted-foreground">
                    {rating.ratingValue.toFixed(1)} average across {rating.reviewCount}{" "}
                    {rating.platform} reviews.
                  </p>
                )}
                <div className="mt-6 border-t border-border pt-6">
                  <LicenseVerifyBadge />
                  <CredentialModal />
                </div>
              </div>
            </div>}
          </div>

          <div className="mt-16">
            <TrustBadgeRail />
          </div>
        </div>
      </header>
    </CinematicHero>
  );
}

export function HomePage() {
  const cfg = trustConfig;

  return (
    <TrustProvider config={cfg} className="min-h-screen bg-background text-foreground">
      <SpeakableSchema rendered={Boolean(cfg.voice.answers?.length)} />

      <Hero cfg={cfg} />

      {Boolean(cfg.proof.stats?.length) && (<SectionShell tone="raised">
        <CounterStatBand />
      </SectionShell>)}

      <SectionShell
        eyebrow="What we do"
        title={cfg.labels.serviceMenuTitle}
        lede={clientData.content.serviceIntro}
        id="services"
      >
        <ServiceMenuGrid />
      </SectionShell>

      {Boolean(cfg.proof.reviews?.length) && (<SectionShell tone="raised">
        <ReviewMarquee />
      </SectionShell>)}

      {Boolean(cfg.proof.reviews?.length) && (<SectionShell
        eyebrow="Proof, not promises"
        title={cfg.labels.reviewsTitle}
        
        id="reviews"
      >
        <div className="grid gap-8">
          <ReviewSpotlight />
          <ReviewWall />
        </div>
      </SectionShell>)}

      {Boolean(clientData.content.values.length) && (<SectionShell eyebrow="Our approach" title={clientData.content.whyHeadline || 'Our approach'} tone="raised">
        <GuaranteePanel items={clientData.content.values.map((v, i) => ({ id: `value-${i}`, title: v.title, detail: v.body }))} />
      </SectionShell>)}

      {Boolean(cfg.proof.credentials?.length) && (<SectionShell
        eyebrow="Credentials"
        title={cfg.labels.credentialsTitle}
        
        id="credentials"
      >
        <InsuranceProofPanel />
      </SectionShell>)}

      {Boolean(cfg.proof.gallery?.length) && (<SectionShell eyebrow="Recent work" title={cfg.labels.galleryTitle} tone="raised" id="work">
        <PortfolioLightbox />
      </SectionShell>)}

      {Boolean(cfg.location.serviceAreas?.length || clientData.trust.mapUrl || sitePlan?.localPresence?.mapAndDirections?.geo?.verified) && (<SectionShell
        eyebrow="Where we work"
        title="Service areas"
        
        id="areas"
      >
        <div className="grid gap-10">
          <LocalMap />
          <ServiceAreaBanner />
        </div>
      </SectionShell>)}

      {Boolean(clientConfig.maps.writeReviewUrl) && (<SectionShell tone="raised" id="leave-a-review">
        <ReviewRequestPanel />
      </SectionShell>)}

      {Boolean(cfg.voice.answers?.length) && (<SectionShell
        eyebrow="Asked and answered"
        title="Questions people actually ask"
        
        id="faq"
      >
        <VoiceAnswerBlock />
      </SectionShell>)}

      {Boolean(cfg.availability.emergency?.available) && (<SectionShell>
        <EmergencyCTABand />
      </SectionShell>)}

      <SectionShell id="about" eyebrow="About" title={clientData.content.whyHeadline || cfg.business.name}>
        <ClientCopy text={sitePlan?.content?.["about"] || clientData.content.about} />
      </SectionShell>
      <ContactBand />

      <SectionShell tone="raised">
        <SeoProofBlock />
      </SectionShell>

      <footer className="border-t border-border px-5 py-16 sm:px-8">
        <div className="mx-auto grid w-full max-w-[1180px] gap-10 sm:grid-cols-3">
          <div>
            <BrandMark />
            <p className="mt-4 max-w-xs text-sm text-muted-foreground">
              {cfg.business.tagline}
            </p>
            <a
              href={`tel:${cfg.contact.phone}`}
              className="mt-4 inline-block text-base font-semibold text-mint hover:underline"
            >
              {cfg.contact.phoneDisplay}
            </a>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.28em] text-mint">Follow</p>
            <div className="mt-4">
              {clientData.trust.socials.map(url => <a key={url} href={url} rel="noreferrer" className="block py-2">{new URL(url).hostname}</a>)}
            </div>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.28em] text-mint">Hours</p>
            <HoursText />
          </div>
        </div>
        <p className="mx-auto mt-12 w-full max-w-[1180px] text-xs text-muted-foreground">
          © {new Date().getFullYear()} {cfg.business.name}.
        </p>
      </footer>

      <ProofStickyBar />
      <BookNowSticky />
      {/* Universal AI concierge — identical in every mirror, facts come from the two config files. */}

    </TrustProvider>
  );
}
