/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeServiceZionCrossroadsVaRouteImport } from './routes/tree-service-zion-crossroads-va'
import { Route as TreeServiceStanardsvilleVaRouteImport } from './routes/tree-service-stanardsville-va'
import { Route as TreeServiceRuckersvilleVaRouteImport } from './routes/tree-service-ruckersville-va'
import { Route as TreeServiceOrangeVaRouteImport } from './routes/tree-service-orange-va'
import { Route as TreeServiceMadisonVaRouteImport } from './routes/tree-service-madison-va'
import { Route as TreeServiceLouisaVaRouteImport } from './routes/tree-service-louisa-va'
import { Route as TreeServiceGordonsvilleVaRouteImport } from './routes/tree-service-gordonsville-va'
import { Route as TreeServiceCharlottesvilleVaRouteImport } from './routes/tree-service-charlottesville-va'
import { Route as TreeRemovalStumpGrindingRouteImport } from './routes/tree-removal-stump-grinding'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as EmergencyTreeServiceRouteImport } from './routes/emergency-tree-service'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesTreePruningRouteImport } from './routes/services/tree-pruning'
import { Route as ServicesStormDamageCleanupRouteImport } from './routes/services/storm-damage-cleanup'
import { Route as ServicesSnowRemovalRouteImport } from './routes/services/snow-removal'
import { Route as ServicesMulchingRouteImport } from './routes/services/mulching'
import { Route as ServicesLotClearingRouteImport } from './routes/services/lot-clearing'
import { Route as ServicesLandscapeMaintenanceRouteImport } from './routes/services/landscape-maintenance'
import { Route as ServicesBucketTruckServiceRouteImport } from './routes/services/bucket-truck-service'
import { Route as ServicesBrushHoggingRouteImport } from './routes/services/brush-hogging'

const TreeServiceZionCrossroadsVaRoute =
  TreeServiceZionCrossroadsVaRouteImport.update({
    id: '/tree-service-zion-crossroads-va',
    path: '/tree-service-zion-crossroads-va',
    getParentRoute: () => rootRouteImport,
  } as any)
const TreeServiceStanardsvilleVaRoute =
  TreeServiceStanardsvilleVaRouteImport.update({
    id: '/tree-service-stanardsville-va',
    path: '/tree-service-stanardsville-va',
    getParentRoute: () => rootRouteImport,
  } as any)
const TreeServiceRuckersvilleVaRoute =
  TreeServiceRuckersvilleVaRouteImport.update({
    id: '/tree-service-ruckersville-va',
    path: '/tree-service-ruckersville-va',
    getParentRoute: () => rootRouteImport,
  } as any)
const TreeServiceOrangeVaRoute = TreeServiceOrangeVaRouteImport.update({
  id: '/tree-service-orange-va',
  path: '/tree-service-orange-va',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeServiceMadisonVaRoute = TreeServiceMadisonVaRouteImport.update({
  id: '/tree-service-madison-va',
  path: '/tree-service-madison-va',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeServiceLouisaVaRoute = TreeServiceLouisaVaRouteImport.update({
  id: '/tree-service-louisa-va',
  path: '/tree-service-louisa-va',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeServiceGordonsvilleVaRoute =
  TreeServiceGordonsvilleVaRouteImport.update({
    id: '/tree-service-gordonsville-va',
    path: '/tree-service-gordonsville-va',
    getParentRoute: () => rootRouteImport,
  } as any)
const TreeServiceCharlottesvilleVaRoute =
  TreeServiceCharlottesvilleVaRouteImport.update({
    id: '/tree-service-charlottesville-va',
    path: '/tree-service-charlottesville-va',
    getParentRoute: () => rootRouteImport,
  } as any)
const TreeRemovalStumpGrindingRoute =
  TreeRemovalStumpGrindingRouteImport.update({
    id: '/tree-removal-stump-grinding',
    path: '/tree-removal-stump-grinding',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyTreeServiceRoute = EmergencyTreeServiceRouteImport.update({
  id: '/emergency-tree-service',
  path: '/emergency-tree-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTreePruningRoute = ServicesTreePruningRouteImport.update({
  id: '/services/tree-pruning',
  path: '/services/tree-pruning',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStormDamageCleanupRoute =
  ServicesStormDamageCleanupRouteImport.update({
    id: '/services/storm-damage-cleanup',
    path: '/services/storm-damage-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSnowRemovalRoute = ServicesSnowRemovalRouteImport.update({
  id: '/services/snow-removal',
  path: '/services/snow-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMulchingRoute = ServicesMulchingRouteImport.update({
  id: '/services/mulching',
  path: '/services/mulching',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLotClearingRoute = ServicesLotClearingRouteImport.update({
  id: '/services/lot-clearing',
  path: '/services/lot-clearing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLandscapeMaintenanceRoute =
  ServicesLandscapeMaintenanceRouteImport.update({
    id: '/services/landscape-maintenance',
    path: '/services/landscape-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBucketTruckServiceRoute =
  ServicesBucketTruckServiceRouteImport.update({
    id: '/services/bucket-truck-service',
    path: '/services/bucket-truck-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBrushHoggingRoute = ServicesBrushHoggingRouteImport.update({
  id: '/services/brush-hogging',
  path: '/services/brush-hogging',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emergency-tree-service': typeof EmergencyTreeServiceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tree-removal-stump-grinding': typeof TreeRemovalStumpGrindingRoute
  '/tree-service-charlottesville-va': typeof TreeServiceCharlottesvilleVaRoute
  '/tree-service-gordonsville-va': typeof TreeServiceGordonsvilleVaRoute
  '/tree-service-louisa-va': typeof TreeServiceLouisaVaRoute
  '/tree-service-madison-va': typeof TreeServiceMadisonVaRoute
  '/tree-service-orange-va': typeof TreeServiceOrangeVaRoute
  '/tree-service-ruckersville-va': typeof TreeServiceRuckersvilleVaRoute
  '/tree-service-stanardsville-va': typeof TreeServiceStanardsvilleVaRoute
  '/tree-service-zion-crossroads-va': typeof TreeServiceZionCrossroadsVaRoute
  '/services/brush-hogging': typeof ServicesBrushHoggingRoute
  '/services/bucket-truck-service': typeof ServicesBucketTruckServiceRoute
  '/services/landscape-maintenance': typeof ServicesLandscapeMaintenanceRoute
  '/services/lot-clearing': typeof ServicesLotClearingRoute
  '/services/mulching': typeof ServicesMulchingRoute
  '/services/snow-removal': typeof ServicesSnowRemovalRoute
  '/services/storm-damage-cleanup': typeof ServicesStormDamageCleanupRoute
  '/services/tree-pruning': typeof ServicesTreePruningRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emergency-tree-service': typeof EmergencyTreeServiceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tree-removal-stump-grinding': typeof TreeRemovalStumpGrindingRoute
  '/tree-service-charlottesville-va': typeof TreeServiceCharlottesvilleVaRoute
  '/tree-service-gordonsville-va': typeof TreeServiceGordonsvilleVaRoute
  '/tree-service-louisa-va': typeof TreeServiceLouisaVaRoute
  '/tree-service-madison-va': typeof TreeServiceMadisonVaRoute
  '/tree-service-orange-va': typeof TreeServiceOrangeVaRoute
  '/tree-service-ruckersville-va': typeof TreeServiceRuckersvilleVaRoute
  '/tree-service-stanardsville-va': typeof TreeServiceStanardsvilleVaRoute
  '/tree-service-zion-crossroads-va': typeof TreeServiceZionCrossroadsVaRoute
  '/services/brush-hogging': typeof ServicesBrushHoggingRoute
  '/services/bucket-truck-service': typeof ServicesBucketTruckServiceRoute
  '/services/landscape-maintenance': typeof ServicesLandscapeMaintenanceRoute
  '/services/lot-clearing': typeof ServicesLotClearingRoute
  '/services/mulching': typeof ServicesMulchingRoute
  '/services/snow-removal': typeof ServicesSnowRemovalRoute
  '/services/storm-damage-cleanup': typeof ServicesStormDamageCleanupRoute
  '/services/tree-pruning': typeof ServicesTreePruningRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emergency-tree-service': typeof EmergencyTreeServiceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tree-removal-stump-grinding': typeof TreeRemovalStumpGrindingRoute
  '/tree-service-charlottesville-va': typeof TreeServiceCharlottesvilleVaRoute
  '/tree-service-gordonsville-va': typeof TreeServiceGordonsvilleVaRoute
  '/tree-service-louisa-va': typeof TreeServiceLouisaVaRoute
  '/tree-service-madison-va': typeof TreeServiceMadisonVaRoute
  '/tree-service-orange-va': typeof TreeServiceOrangeVaRoute
  '/tree-service-ruckersville-va': typeof TreeServiceRuckersvilleVaRoute
  '/tree-service-stanardsville-va': typeof TreeServiceStanardsvilleVaRoute
  '/tree-service-zion-crossroads-va': typeof TreeServiceZionCrossroadsVaRoute
  '/services/brush-hogging': typeof ServicesBrushHoggingRoute
  '/services/bucket-truck-service': typeof ServicesBucketTruckServiceRoute
  '/services/landscape-maintenance': typeof ServicesLandscapeMaintenanceRoute
  '/services/lot-clearing': typeof ServicesLotClearingRoute
  '/services/mulching': typeof ServicesMulchingRoute
  '/services/snow-removal': typeof ServicesSnowRemovalRoute
  '/services/storm-damage-cleanup': typeof ServicesStormDamageCleanupRoute
  '/services/tree-pruning': typeof ServicesTreePruningRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/emergency-tree-service'
    | '/robots.txt'
    | '/service-area'
    | '/sitemap.xml'
    | '/tree-removal-stump-grinding'
    | '/tree-service-charlottesville-va'
    | '/tree-service-gordonsville-va'
    | '/tree-service-louisa-va'
    | '/tree-service-madison-va'
    | '/tree-service-orange-va'
    | '/tree-service-ruckersville-va'
    | '/tree-service-stanardsville-va'
    | '/tree-service-zion-crossroads-va'
    | '/services/brush-hogging'
    | '/services/bucket-truck-service'
    | '/services/landscape-maintenance'
    | '/services/lot-clearing'
    | '/services/mulching'
    | '/services/snow-removal'
    | '/services/storm-damage-cleanup'
    | '/services/tree-pruning'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/emergency-tree-service'
    | '/robots.txt'
    | '/service-area'
    | '/sitemap.xml'
    | '/tree-removal-stump-grinding'
    | '/tree-service-charlottesville-va'
    | '/tree-service-gordonsville-va'
    | '/tree-service-louisa-va'
    | '/tree-service-madison-va'
    | '/tree-service-orange-va'
    | '/tree-service-ruckersville-va'
    | '/tree-service-stanardsville-va'
    | '/tree-service-zion-crossroads-va'
    | '/services/brush-hogging'
    | '/services/bucket-truck-service'
    | '/services/landscape-maintenance'
    | '/services/lot-clearing'
    | '/services/mulching'
    | '/services/snow-removal'
    | '/services/storm-damage-cleanup'
    | '/services/tree-pruning'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/emergency-tree-service'
    | '/robots.txt'
    | '/service-area'
    | '/sitemap.xml'
    | '/tree-removal-stump-grinding'
    | '/tree-service-charlottesville-va'
    | '/tree-service-gordonsville-va'
    | '/tree-service-louisa-va'
    | '/tree-service-madison-va'
    | '/tree-service-orange-va'
    | '/tree-service-ruckersville-va'
    | '/tree-service-stanardsville-va'
    | '/tree-service-zion-crossroads-va'
    | '/services/brush-hogging'
    | '/services/bucket-truck-service'
    | '/services/landscape-maintenance'
    | '/services/lot-clearing'
    | '/services/mulching'
    | '/services/snow-removal'
    | '/services/storm-damage-cleanup'
    | '/services/tree-pruning'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EmergencyTreeServiceRoute: typeof EmergencyTreeServiceRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TreeRemovalStumpGrindingRoute: typeof TreeRemovalStumpGrindingRoute
  TreeServiceCharlottesvilleVaRoute: typeof TreeServiceCharlottesvilleVaRoute
  TreeServiceGordonsvilleVaRoute: typeof TreeServiceGordonsvilleVaRoute
  TreeServiceLouisaVaRoute: typeof TreeServiceLouisaVaRoute
  TreeServiceMadisonVaRoute: typeof TreeServiceMadisonVaRoute
  TreeServiceOrangeVaRoute: typeof TreeServiceOrangeVaRoute
  TreeServiceRuckersvilleVaRoute: typeof TreeServiceRuckersvilleVaRoute
  TreeServiceStanardsvilleVaRoute: typeof TreeServiceStanardsvilleVaRoute
  TreeServiceZionCrossroadsVaRoute: typeof TreeServiceZionCrossroadsVaRoute
  ServicesBrushHoggingRoute: typeof ServicesBrushHoggingRoute
  ServicesBucketTruckServiceRoute: typeof ServicesBucketTruckServiceRoute
  ServicesLandscapeMaintenanceRoute: typeof ServicesLandscapeMaintenanceRoute
  ServicesLotClearingRoute: typeof ServicesLotClearingRoute
  ServicesMulchingRoute: typeof ServicesMulchingRoute
  ServicesSnowRemovalRoute: typeof ServicesSnowRemovalRoute
  ServicesStormDamageCleanupRoute: typeof ServicesStormDamageCleanupRoute
  ServicesTreePruningRoute: typeof ServicesTreePruningRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree-service-zion-crossroads-va': {
      id: '/tree-service-zion-crossroads-va'
      path: '/tree-service-zion-crossroads-va'
      fullPath: '/tree-service-zion-crossroads-va'
      preLoaderRoute: typeof TreeServiceZionCrossroadsVaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-service-stanardsville-va': {
      id: '/tree-service-stanardsville-va'
      path: '/tree-service-stanardsville-va'
      fullPath: '/tree-service-stanardsville-va'
      preLoaderRoute: typeof TreeServiceStanardsvilleVaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-service-ruckersville-va': {
      id: '/tree-service-ruckersville-va'
      path: '/tree-service-ruckersville-va'
      fullPath: '/tree-service-ruckersville-va'
      preLoaderRoute: typeof TreeServiceRuckersvilleVaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-service-orange-va': {
      id: '/tree-service-orange-va'
      path: '/tree-service-orange-va'
      fullPath: '/tree-service-orange-va'
      preLoaderRoute: typeof TreeServiceOrangeVaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-service-madison-va': {
      id: '/tree-service-madison-va'
      path: '/tree-service-madison-va'
      fullPath: '/tree-service-madison-va'
      preLoaderRoute: typeof TreeServiceMadisonVaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-service-louisa-va': {
      id: '/tree-service-louisa-va'
      path: '/tree-service-louisa-va'
      fullPath: '/tree-service-louisa-va'
      preLoaderRoute: typeof TreeServiceLouisaVaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-service-gordonsville-va': {
      id: '/tree-service-gordonsville-va'
      path: '/tree-service-gordonsville-va'
      fullPath: '/tree-service-gordonsville-va'
      preLoaderRoute: typeof TreeServiceGordonsvilleVaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-service-charlottesville-va': {
      id: '/tree-service-charlottesville-va'
      path: '/tree-service-charlottesville-va'
      fullPath: '/tree-service-charlottesville-va'
      preLoaderRoute: typeof TreeServiceCharlottesvilleVaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-removal-stump-grinding': {
      id: '/tree-removal-stump-grinding'
      path: '/tree-removal-stump-grinding'
      fullPath: '/tree-removal-stump-grinding'
      preLoaderRoute: typeof TreeRemovalStumpGrindingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-tree-service': {
      id: '/emergency-tree-service'
      path: '/emergency-tree-service'
      fullPath: '/emergency-tree-service'
      preLoaderRoute: typeof EmergencyTreeServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tree-pruning': {
      id: '/services/tree-pruning'
      path: '/services/tree-pruning'
      fullPath: '/services/tree-pruning'
      preLoaderRoute: typeof ServicesTreePruningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/storm-damage-cleanup': {
      id: '/services/storm-damage-cleanup'
      path: '/services/storm-damage-cleanup'
      fullPath: '/services/storm-damage-cleanup'
      preLoaderRoute: typeof ServicesStormDamageCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/snow-removal': {
      id: '/services/snow-removal'
      path: '/services/snow-removal'
      fullPath: '/services/snow-removal'
      preLoaderRoute: typeof ServicesSnowRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mulching': {
      id: '/services/mulching'
      path: '/services/mulching'
      fullPath: '/services/mulching'
      preLoaderRoute: typeof ServicesMulchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lot-clearing': {
      id: '/services/lot-clearing'
      path: '/services/lot-clearing'
      fullPath: '/services/lot-clearing'
      preLoaderRoute: typeof ServicesLotClearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/landscape-maintenance': {
      id: '/services/landscape-maintenance'
      path: '/services/landscape-maintenance'
      fullPath: '/services/landscape-maintenance'
      preLoaderRoute: typeof ServicesLandscapeMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bucket-truck-service': {
      id: '/services/bucket-truck-service'
      path: '/services/bucket-truck-service'
      fullPath: '/services/bucket-truck-service'
      preLoaderRoute: typeof ServicesBucketTruckServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/brush-hogging': {
      id: '/services/brush-hogging'
      path: '/services/brush-hogging'
      fullPath: '/services/brush-hogging'
      preLoaderRoute: typeof ServicesBrushHoggingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EmergencyTreeServiceRoute: EmergencyTreeServiceRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TreeRemovalStumpGrindingRoute: TreeRemovalStumpGrindingRoute,
  TreeServiceCharlottesvilleVaRoute: TreeServiceCharlottesvilleVaRoute,
  TreeServiceGordonsvilleVaRoute: TreeServiceGordonsvilleVaRoute,
  TreeServiceLouisaVaRoute: TreeServiceLouisaVaRoute,
  TreeServiceMadisonVaRoute: TreeServiceMadisonVaRoute,
  TreeServiceOrangeVaRoute: TreeServiceOrangeVaRoute,
  TreeServiceRuckersvilleVaRoute: TreeServiceRuckersvilleVaRoute,
  TreeServiceStanardsvilleVaRoute: TreeServiceStanardsvilleVaRoute,
  TreeServiceZionCrossroadsVaRoute: TreeServiceZionCrossroadsVaRoute,
  ServicesBrushHoggingRoute: ServicesBrushHoggingRoute,
  ServicesBucketTruckServiceRoute: ServicesBucketTruckServiceRoute,
  ServicesLandscapeMaintenanceRoute: ServicesLandscapeMaintenanceRoute,
  ServicesLotClearingRoute: ServicesLotClearingRoute,
  ServicesMulchingRoute: ServicesMulchingRoute,
  ServicesSnowRemovalRoute: ServicesSnowRemovalRoute,
  ServicesStormDamageCleanupRoute: ServicesStormDamageCleanupRoute,
  ServicesTreePruningRoute: ServicesTreePruningRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
