import test from "node:test";
import assert from "node:assert/strict";
import { enforceBusinessTruth } from "../lib/business-truth.mjs";

const recovered = { business:{name:"Red Clay Fencing",category:"landscaping",city:"fence contractor Moultrie",state:"GA"}, services:["Fences installed","Street View","Service Area"], enrichment_sources:{copy:{value:"Red Clay Fencing — Wood, Iron & Chain Link Fences in Moultrie, GA. Custom fence installation and ranch rail."}}, media:{catalog:[{url:"https://www.google.com/maps/vt/tile"},{url:"https://redclay-fences.lovable.app/assets/hero-fence.jpg"}]}, source_evidence:[{field:"category",value:"landscaping"}] };
test("recovered Red Clay truth cannot cross-contaminate",()=>{const t=enforceBusinessTruth(recovered);assert.equal(t.business.category,"fencing");assert.equal(t.business.city,"Moultrie");assert.deepEqual(t.services,["Fences installed"]);assert.equal(t.media.catalog.length,1);assert.doesNotMatch(JSON.stringify(t),/Street View|maps\/vt/);});
test("landscaping remains landscaping",()=>{const t=enforceBusinessTruth({business:{name:"Green Yard",category:"landscaping",city:"Sacramento",state:"CA"},services:["Lawn care","Chain link fencing"],enrichment_sources:{copy:{value:"Lawn care, irrigation, planting and yard cleanup in Sacramento, CA."}}});assert.equal(t.business.category,"landscaping");assert.deepEqual(t.services,["Lawn care"]);});
test("verified landscape service suffixes survive truth filtering",()=>{const t=enforceBusinessTruth({business:{name:"Signature Landscape",category:"landscaping",city:"Mission Viejo",state:"CA"},services:["Outdoor Kitchen","Pavers Stone","Stamped Concrete","Retaining Walls"],enrichment_sources:{copy:{value:"Outdoor kitchens, pavers, concrete, and retaining walls in Mission Viejo, CA."}}});assert.deepEqual(t.services,["Outdoor Kitchen","Pavers Stone","Stamped Concrete","Retaining Walls"]);});
test("unrelated vertical does not inherit trade facts",()=>{const t=enforceBusinessTruth({business:{name:"Volt Co",category:"electrical",city:"Plano",state:"TX"},services:["Panel upgrades","Lawn care"],enrichment_sources:{copy:{value:"Electrical panel upgrades and EV chargers in Plano, TX."}}});assert.equal(t.business.category,"electrical");assert.deepEqual(t.services,["Panel upgrades"]);});
test("bare categories and unowned web-search logos are rejected",()=>{const t=enforceBusinessTruth({business:{name:"Barriga Landscaping",category:"landscaping",city:"Sacramento",state:"CA"},services:["Barriga Landscaping","Landscaper","Street View"]},{sourceAssets:[{kind:"logo",source:"web-search",url:"https://cdn.example.com/random.png"}]});assert.deepEqual(t.services,[]);assert.equal(t.logo_source,undefined)});
test("identity-matched official logo host is accepted",()=>{const t=enforceBusinessTruth({business:{name:"Red Clay Fencing",category:"fencing",city:"Moultrie",state:"GA"},services:[]},{sourceAssets:[{kind:"logo",source:"web-search",url:"https://redclayfencing.com/assets/logo.png",provenance:{source_url:"https://redclayfencing.com/",source_host:"redclayfencing.com",owner_key:"red-clay"}}]});assert.equal(t.logo_source.url,"https://redclayfencing.com/assets/logo.png");assert.match(t.logo_source.checksum,/^[a-f0-9]{64}$/)});
test("trade words cannot make a matching official logo look foreign",()=>{const t=enforceBusinessTruth({business:{name:"Acme Lawn Services",category:"landscaping",city:"Irvine",state:"CA"},services:[]},{sourceAssets:[{kind:"logo",source:"business-site",url:"https://cdn.example.net/acme-logo.png",provenance:{source_url:"https://acmelawn.com/",source_host:"acmelawn.com",owner_key:"acme"}}]});assert.equal(t.logo_source.url,"https://cdn.example.net/acme-logo.png")});
test("an explicitly rejected old logo cannot beat the approved current logo",()=>{const provenance={source_url:"https://acmelawn.com/",source_host:"acmelawn.com",owner_key:"acme"};const t=enforceBusinessTruth({business:{name:"Acme Lawn Services",category:"landscaping",city:"Irvine",state:"CA"},services:[]},{sourceAssets:[{kind:"logo",approved:false,url:"https://cdn.example.net/retired-acme-logo.svg",provenance},{kind:"logo",approved:true,url:"https://cdn.example.net/current-acme-logo.svg",provenance}]});assert.equal(t.logo_source.url,"https://cdn.example.net/current-acme-logo.svg")});
test("Tekline logo cannot be relabeled as Sunset business-site media",()=>{const t=enforceBusinessTruth({business:{name:"Sunset Landscaping",category:"landscaping",city:"Irvine",state:"CA"},services:[]},{sourceAssets:[{kind:"logo",source:"business-site",origin:"business-evidence",url:"https://cdn.tekline.com/brand/tekline-logo.png",provenance:{source_url:"https://tekline.com/",source_host:"tekline.com",owner_key:"tekline"}}]});assert.equal(t.logo_source,undefined);assert.equal(t.v7_logo,undefined)});
test("authenticated owner upload remains valid without a public host",()=>{const t=enforceBusinessTruth({business:{name:"Sunset Landscaping",category:"landscaping",city:"Irvine",state:"CA"},services:[],v7_logo:{url:"/media/sunset-logo.png",origin:"upload"}});assert.equal(t.logo_source.url,"/media/sunset-logo.png")});
test("owner-supplied labels without authenticated upload provenance are rejected",()=>{const t=enforceBusinessTruth({business:{name:"Sunset Landscaping",category:"landscaping",city:"Irvine",state:"CA"},services:[]},{sourceAssets:[{kind:"logo",source:"owner-supplied",origin:"owner-supplied",url:"https://cdn.example.com/sunset-logo.png"}]});assert.equal(t.logo_source,undefined)});
