/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BbbCategoriesRouteImport } from './routes/bbb-categories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServiceAreasSlugRouteImport } from './routes/service-areas.$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BbbCategoriesRoute = BbbCategoriesRouteImport.update({
  id: '/bbb-categories',
  path: '/bbb-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ServiceAreasSlugRoute = ServiceAreasSlugRouteImport.update({
  id: '/service-areas/$slug',
  path: '/service-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bbb-categories': typeof BbbCategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bbb-categories': typeof BbbCategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/service-areas': typeof ServiceAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bbb-categories': typeof BbbCategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bbb-categories'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/services'
    | '/service-areas/$slug'
    | '/services/$slug'
    | '/service-areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bbb-categories'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/services'
    | '/service-areas/$slug'
    | '/services/$slug'
    | '/service-areas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bbb-categories'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/services'
    | '/service-areas/$slug'
    | '/services/$slug'
    | '/service-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BbbCategoriesRoute: typeof BbbCategoriesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ServiceAreasSlugRoute: typeof ServiceAreasSlugRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbb-categories': {
      id: '/bbb-categories'
      path: '/bbb-categories'
      fullPath: '/bbb-categories'
      preLoaderRoute: typeof BbbCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/service-areas/$slug': {
      id: '/service-areas/$slug'
      path: '/service-areas/$slug'
      fullPath: '/service-areas/$slug'
      preLoaderRoute: typeof ServiceAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BbbCategoriesRoute: BbbCategoriesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ServiceAreasSlugRoute: ServiceAreasSlugRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
