/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRemovalRouteImport } from './routes/tree-removal'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LawnLandscapingRouteImport } from './routes/lawn-landscaping'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiDottxtRouteImport } from './routes/ai[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexnowKeyKeyDottxtRouteImport } from './routes/indexnow-key.$key[.]txt'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiIndexnowRouteImport } from './routes/api/indexnow'

const TreeRemovalRoute = TreeRemovalRouteImport.update({
  id: '/tree-removal',
  path: '/tree-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LawnLandscapingRoute = LawnLandscapingRouteImport.update({
  id: '/lawn-landscaping',
  path: '/lawn-landscaping',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDottxtRoute = AiDottxtRouteImport.update({
  id: '/ai.txt',
  path: '/ai.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexnowKeyKeyDottxtRoute = IndexnowKeyKeyDottxtRouteImport.update({
  id: '/indexnow-key/$key.txt',
  path: '/indexnow-key/$key.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexnowRoute = ApiIndexnowRouteImport.update({
  id: '/api/indexnow',
  path: '/api/indexnow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai.txt': typeof AiDottxtRoute
  '/contact': typeof ContactRoute
  '/lawn-landscaping': typeof LawnLandscapingRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tree-removal': typeof TreeRemovalRoute
  '/api/indexnow': typeof ApiIndexnowRoute
  '/api/lead': typeof ApiLeadRoute
  '/indexnow-key/$key.txt': typeof IndexnowKeyKeyDottxtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai.txt': typeof AiDottxtRoute
  '/contact': typeof ContactRoute
  '/lawn-landscaping': typeof LawnLandscapingRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tree-removal': typeof TreeRemovalRoute
  '/api/indexnow': typeof ApiIndexnowRoute
  '/api/lead': typeof ApiLeadRoute
  '/indexnow-key/$key.txt': typeof IndexnowKeyKeyDottxtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai.txt': typeof AiDottxtRoute
  '/contact': typeof ContactRoute
  '/lawn-landscaping': typeof LawnLandscapingRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tree-removal': typeof TreeRemovalRoute
  '/api/indexnow': typeof ApiIndexnowRoute
  '/api/lead': typeof ApiLeadRoute
  '/indexnow-key/$key.txt': typeof IndexnowKeyKeyDottxtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai.txt'
    | '/contact'
    | '/lawn-landscaping'
    | '/llms.txt'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/tree-removal'
    | '/api/indexnow'
    | '/api/lead'
    | '/indexnow-key/$key.txt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai.txt'
    | '/contact'
    | '/lawn-landscaping'
    | '/llms.txt'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/tree-removal'
    | '/api/indexnow'
    | '/api/lead'
    | '/indexnow-key/$key.txt'
  id:
    | '__root__'
    | '/'
    | '/ai.txt'
    | '/contact'
    | '/lawn-landscaping'
    | '/llms.txt'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/tree-removal'
    | '/api/indexnow'
    | '/api/lead'
    | '/indexnow-key/$key.txt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDottxtRoute: typeof AiDottxtRoute
  ContactRoute: typeof ContactRoute
  LawnLandscapingRoute: typeof LawnLandscapingRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TreeRemovalRoute: typeof TreeRemovalRoute
  ApiIndexnowRoute: typeof ApiIndexnowRoute
  ApiLeadRoute: typeof ApiLeadRoute
  IndexnowKeyKeyDottxtRoute: typeof IndexnowKeyKeyDottxtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree-removal': {
      id: '/tree-removal'
      path: '/tree-removal'
      fullPath: '/tree-removal'
      preLoaderRoute: typeof TreeRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawn-landscaping': {
      id: '/lawn-landscaping'
      path: '/lawn-landscaping'
      fullPath: '/lawn-landscaping'
      preLoaderRoute: typeof LawnLandscapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai.txt': {
      id: '/ai.txt'
      path: '/ai.txt'
      fullPath: '/ai.txt'
      preLoaderRoute: typeof AiDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexnow-key/$key.txt': {
      id: '/indexnow-key/$key.txt'
      path: '/indexnow-key/$key.txt'
      fullPath: '/indexnow-key/$key.txt'
      preLoaderRoute: typeof IndexnowKeyKeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indexnow': {
      id: '/api/indexnow'
      path: '/api/indexnow'
      fullPath: '/api/indexnow'
      preLoaderRoute: typeof ApiIndexnowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDottxtRoute: AiDottxtRoute,
  ContactRoute: ContactRoute,
  LawnLandscapingRoute: LawnLandscapingRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TreeRemovalRoute: TreeRemovalRoute,
  ApiIndexnowRoute: ApiIndexnowRoute,
  ApiLeadRoute: ApiLeadRoute,
  IndexnowKeyKeyDottxtRoute: IndexnowKeyKeyDottxtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
