/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as HomeRenovationRouteImport } from './routes/home-renovation'
import { Route as FoundationsExcavationRouteImport } from './routes/foundations-excavation'
import { Route as FlooringServicesRouteImport } from './routes/flooring-services'
import { Route as FlatworkDrivewaysRouteImport } from './routes/flatwork-driveways'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConcreteDemolitionRouteImport } from './routes/concrete-demolition'
import { Route as CommercialRenovationRouteImport } from './routes/commercial-renovation'
import { Route as CommercialConcreteRouteImport } from './routes/commercial-concrete'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreaIndexRouteImport } from './routes/service-area.index'

const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRenovationRoute = HomeRenovationRouteImport.update({
  id: '/home-renovation',
  path: '/home-renovation',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsExcavationRoute = FoundationsExcavationRouteImport.update({
  id: '/foundations-excavation',
  path: '/foundations-excavation',
  getParentRoute: () => rootRouteImport,
} as any)
const FlooringServicesRoute = FlooringServicesRouteImport.update({
  id: '/flooring-services',
  path: '/flooring-services',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatworkDrivewaysRoute = FlatworkDrivewaysRouteImport.update({
  id: '/flatwork-driveways',
  path: '/flatwork-driveways',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcreteDemolitionRoute = ConcreteDemolitionRouteImport.update({
  id: '/concrete-demolition',
  path: '/concrete-demolition',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRenovationRoute = CommercialRenovationRouteImport.update({
  id: '/commercial-renovation',
  path: '/commercial-renovation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialConcreteRoute = CommercialConcreteRouteImport.update({
  id: '/commercial-concrete',
  path: '/commercial-concrete',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaIndexRoute = ServiceAreaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceAreaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-concrete': typeof CommercialConcreteRoute
  '/commercial-renovation': typeof CommercialRenovationRoute
  '/concrete-demolition': typeof ConcreteDemolitionRoute
  '/contact': typeof ContactRoute
  '/flatwork-driveways': typeof FlatworkDrivewaysRoute
  '/flooring-services': typeof FlooringServicesRoute
  '/foundations-excavation': typeof FoundationsExcavationRoute
  '/home-renovation': typeof HomeRenovationRoute
  '/service-area': typeof ServiceAreaRouteWithChildren
  '/service-area/': typeof ServiceAreaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-concrete': typeof CommercialConcreteRoute
  '/commercial-renovation': typeof CommercialRenovationRoute
  '/concrete-demolition': typeof ConcreteDemolitionRoute
  '/contact': typeof ContactRoute
  '/flatwork-driveways': typeof FlatworkDrivewaysRoute
  '/flooring-services': typeof FlooringServicesRoute
  '/foundations-excavation': typeof FoundationsExcavationRoute
  '/home-renovation': typeof HomeRenovationRoute
  '/service-area': typeof ServiceAreaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial-concrete': typeof CommercialConcreteRoute
  '/commercial-renovation': typeof CommercialRenovationRoute
  '/concrete-demolition': typeof ConcreteDemolitionRoute
  '/contact': typeof ContactRoute
  '/flatwork-driveways': typeof FlatworkDrivewaysRoute
  '/flooring-services': typeof FlooringServicesRoute
  '/foundations-excavation': typeof FoundationsExcavationRoute
  '/home-renovation': typeof HomeRenovationRoute
  '/service-area': typeof ServiceAreaRouteWithChildren
  '/service-area/': typeof ServiceAreaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commercial-concrete'
    | '/commercial-renovation'
    | '/concrete-demolition'
    | '/contact'
    | '/flatwork-driveways'
    | '/flooring-services'
    | '/foundations-excavation'
    | '/home-renovation'
    | '/service-area'
    | '/service-area/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commercial-concrete'
    | '/commercial-renovation'
    | '/concrete-demolition'
    | '/contact'
    | '/flatwork-driveways'
    | '/flooring-services'
    | '/foundations-excavation'
    | '/home-renovation'
    | '/service-area'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commercial-concrete'
    | '/commercial-renovation'
    | '/concrete-demolition'
    | '/contact'
    | '/flatwork-driveways'
    | '/flooring-services'
    | '/foundations-excavation'
    | '/home-renovation'
    | '/service-area'
    | '/service-area/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommercialConcreteRoute: typeof CommercialConcreteRoute
  CommercialRenovationRoute: typeof CommercialRenovationRoute
  ConcreteDemolitionRoute: typeof ConcreteDemolitionRoute
  ContactRoute: typeof ContactRoute
  FlatworkDrivewaysRoute: typeof FlatworkDrivewaysRoute
  FlooringServicesRoute: typeof FlooringServicesRoute
  FoundationsExcavationRoute: typeof FoundationsExcavationRoute
  HomeRenovationRoute: typeof HomeRenovationRoute
  ServiceAreaRoute: typeof ServiceAreaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-renovation': {
      id: '/home-renovation'
      path: '/home-renovation'
      fullPath: '/home-renovation'
      preLoaderRoute: typeof HomeRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations-excavation': {
      id: '/foundations-excavation'
      path: '/foundations-excavation'
      fullPath: '/foundations-excavation'
      preLoaderRoute: typeof FoundationsExcavationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flooring-services': {
      id: '/flooring-services'
      path: '/flooring-services'
      fullPath: '/flooring-services'
      preLoaderRoute: typeof FlooringServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flatwork-driveways': {
      id: '/flatwork-driveways'
      path: '/flatwork-driveways'
      fullPath: '/flatwork-driveways'
      preLoaderRoute: typeof FlatworkDrivewaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concrete-demolition': {
      id: '/concrete-demolition'
      path: '/concrete-demolition'
      fullPath: '/concrete-demolition'
      preLoaderRoute: typeof ConcreteDemolitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-renovation': {
      id: '/commercial-renovation'
      path: '/commercial-renovation'
      fullPath: '/commercial-renovation'
      preLoaderRoute: typeof CommercialRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-concrete': {
      id: '/commercial-concrete'
      path: '/commercial-concrete'
      fullPath: '/commercial-concrete'
      preLoaderRoute: typeof CommercialConcreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area/': {
      id: '/service-area/'
      path: '/'
      fullPath: '/service-area/'
      preLoaderRoute: typeof ServiceAreaIndexRouteImport
      parentRoute: typeof ServiceAreaRoute
    }
  }
}

interface ServiceAreaRouteChildren {
  ServiceAreaIndexRoute: typeof ServiceAreaIndexRoute
}

const ServiceAreaRouteChildren: ServiceAreaRouteChildren = {
  ServiceAreaIndexRoute: ServiceAreaIndexRoute,
}

const ServiceAreaRouteWithChildren = ServiceAreaRoute._addFileChildren(
  ServiceAreaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommercialConcreteRoute: CommercialConcreteRoute,
  CommercialRenovationRoute: CommercialRenovationRoute,
  ConcreteDemolitionRoute: ConcreteDemolitionRoute,
  ContactRoute: ContactRoute,
  FlatworkDrivewaysRoute: FlatworkDrivewaysRoute,
  FlooringServicesRoute: FlooringServicesRoute,
  FoundationsExcavationRoute: FoundationsExcavationRoute,
  HomeRenovationRoute: HomeRenovationRoute,
  ServiceAreaRoute: ServiceAreaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
