/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlasterRouteImport } from './routes/plaster'
import { Route as PaintingRouteImport } from './routes/painting'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DrywallRouteImport } from './routes/drywall'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ServiceSlugRouteImport } from './routes/$serviceSlug'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlasterRoute = PlasterRouteImport.update({
  id: '/plaster',
  path: '/plaster',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingRoute = PaintingRouteImport.update({
  id: '/painting',
  path: '/painting',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DrywallRoute = DrywallRouteImport.update({
  id: '/drywall',
  path: '/drywall',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/drywall': typeof DrywallRoute
  '/gallery': typeof GalleryRoute
  '/painting': typeof PaintingRoute
  '/plaster': typeof PlasterRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/drywall': typeof DrywallRoute
  '/gallery': typeof GalleryRoute
  '/painting': typeof PaintingRoute
  '/plaster': typeof PlasterRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/drywall': typeof DrywallRoute
  '/gallery': typeof GalleryRoute
  '/painting': typeof PaintingRoute
  '/plaster': typeof PlasterRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$serviceSlug'
    | '/about'
    | '/contact'
    | '/drywall'
    | '/gallery'
    | '/painting'
    | '/plaster'
    | '/privacy-policy'
    | '/reviews'
    | '/service-area'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$serviceSlug'
    | '/about'
    | '/contact'
    | '/drywall'
    | '/gallery'
    | '/painting'
    | '/plaster'
    | '/privacy-policy'
    | '/reviews'
    | '/service-area'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/$serviceSlug'
    | '/about'
    | '/contact'
    | '/drywall'
    | '/gallery'
    | '/painting'
    | '/plaster'
    | '/privacy-policy'
    | '/reviews'
    | '/service-area'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DrywallRoute: typeof DrywallRoute
  GalleryRoute: typeof GalleryRoute
  PaintingRoute: typeof PaintingRoute
  PlasterRoute: typeof PlasterRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plaster': {
      id: '/plaster'
      path: '/plaster'
      fullPath: '/plaster'
      preLoaderRoute: typeof PlasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painting': {
      id: '/painting'
      path: '/painting'
      fullPath: '/painting'
      preLoaderRoute: typeof PaintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drywall': {
      id: '/drywall'
      path: '/drywall'
      fullPath: '/drywall'
      preLoaderRoute: typeof DrywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serviceSlug': {
      id: '/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/$serviceSlug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DrywallRoute: DrywallRoute,
  GalleryRoute: GalleryRoute,
  PaintingRoute: PaintingRoute,
  PlasterRoute: PlasterRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
